#!/bin/bash

### BEGIN INIT INFO
# Provides:          mpc-autoplay
# Required-Start:    mpc
# Required-Stop:
# Should-Start:
# Should-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Ensures that mpc plays on startup
# Description:       Start an Icecast stream after startup
### END INIT INFO
#
#IP of Icecast Server Neckartailfingen
Host="192.168.1.200"
#IP of Icecast Server Crinitz
#Host="192.168.2.200"
#Port of Icecast Server
Port="8000"
#Name of Stream/Mount Point
Stream="Crinitz"
#duration between pings
Interval=1
#reset wait-counter
wait=0
#logfile
log=/var/log/mpc-startup.log
#timestamp
date=$(date)

. /lib/lsb/init-functions

case "$1" in
    start)
        echo "$date - MPC start" | tee $log > /dev/null
        while true; do
                if ! ping -c 1 -w 1 $Host > /dev/null; then ((wait++))
                        echo -e -n "waiting for response from Streamserver: $wait \r" | tee -a $log
                else
                        echo ""
                        echo "checking for Streamserver: running!" | tee -a $log
                        echo "starting MPC..." | tee -a $log
                        mpc clear > /dev/null
                        mpc repeat on > /dev/null
                        mpc add http://$Host:$Port/$Stream | tee -a $log > /dev/null
                        mpc play | tee -a $log > /dev/null
                        sleep 2 #wait for stream-name
                        wait=0 #reset wait counter
                        while true; do
                                if mpc | grep ERROR > /dev/null; then ((wait++))
                                        echo -e -n "waiting for stream to become ready: $wait \r" | tee -a $log
                                        mpc play | tee -a $log > /dev/null
                                        sleep $Interval
                                else
                                        echo ""
                                        echo "MPC Status:" | tee -a $log
                                        mpc | tee -a $log
                                        echo "success!" | tee -a $log > /dev/null
                                        echo "--------------------------------" | tee -a $log > /dev/null
                                        echo "" | tee -a $log > /dev/null
                                exit 0
                                fi;
                        done
                fi;
                sleep $Interval;
        done
        ;;
    stop)
        echo "stopping mpc..."
        mpc stop > /dev/null
        mpc clear > /dev/null
        mpc repeat off > /dev/null
        echo "done!"
        ;;
    restart)
        echo "stopping MPC..."
                mpc stop > /dev/null
                mpc clear > /dev/null
                mpc repeat off > /dev/null
        echo "done!"
        echo "$date - MPC restart" | tee -a $log > /dev/null
        while true; do
                if ! ping -c 1 -w 1 $Host > /dev/null; then ((wait++))
                        echo -e -n "waiting for response from Streamserver: $wait \r" | tee -a $log
                else
                        echo ""
                        echo "checking for Streamserver: running!" | tee -a $log
                        echo "starting MPC..." | tee -a $log
                        mpc clear > /dev/null
                        mpc repeat on > /dev/null
                        mpc add http://$Host:$Port/$Stream | tee -a $log > /dev/null
                        mpc play | tee -a $log > /dev/null
                        sleep 2 #wait for stream-name
                        wait=0 #reset wait counter
                        while true; do
                                if mpc | grep ERROR > /dev/null; then ((wait++))
                                        echo -e -n "waiting for stream to become ready: $wait \r" | tee -a $log
                                        mpc play | tee -a $log > /dev/null
                                        sleep $Interval
                                else
                                        echo ""
                                        echo "MPC Status:" | tee -a $log
                                        mpc | tee -a $log
                                        echo "success!" | tee -a $log > /dev/null
                                        echo "--------------------------------" | tee -a $log > /dev/null
                                        echo "" | tee -a $log > /dev/null
                                exit 0
                                fi;
                        done
                fi;
                sleep $Interval;
        done
    status)
        echo "Your personal MPC status:" && mpc
        ;;
    *)
        echo "Usage: $0 start|stop|restart|status"
        exit 2
        ;;
esac
